'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IsbInterop.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;Не удалось преобразовать результат к типу {0}.&quot;.
        '''</summary>
        Friend Shared ReadOnly Property CannotCastResultToSpecifiedType() As String
            Get
                Return ResourceManager.GetString("CannotCastResultToSpecifiedType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Не удалось выполнить метод {0} объекта {1}..
        '''</summary>
        Friend Shared ReadOnly Property CannotExecuteObjectMethodTemplate() As String
            Get
                Return ResourceManager.GetString("CannotExecuteObjectMethodTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ошибка получения объекта приложения IS-Builder..
        '''</summary>
        Friend Shared ReadOnly Property CannotGetIsbApplication() As String
            Get
                Return ResourceManager.GetString("CannotGetIsbApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ошибка получения объекта приложения. {0}.
        '''</summary>
        Friend Shared ReadOnly Property CannotGetIsbApplicationTemplate() As String
            Get
                Return ResourceManager.GetString("CannotGetIsbApplicationTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Не удалось получить свойство {0} объекта {1}..
        '''</summary>
        Friend Shared ReadOnly Property CannotGetObjectProperyTemplate() As String
            Get
                Return ResourceManager.GetString("CannotGetObjectProperyTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Не удалось установить свойство {0} объекта {1}..
        '''</summary>
        Friend Shared ReadOnly Property CannotSetObjectProperyTemplate() As String
            Get
                Return ResourceManager.GetString("CannotSetObjectProperyTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Внутренний код ошибки: {0}..
        '''</summary>
        Friend Shared ReadOnly Property InternalErrorCodeStringTemplate() As String
            Get
                Return ResourceManager.GetString("InternalErrorCodeStringTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ошибка удаления установленного ранее ограничения &apos;AddWhere&apos; для набора записей детального раздела справочника..
        '''</summary>
        Friend Shared ReadOnly Property UnableToDeleteDetailDataSetQueryConstraint() As String
            Get
                Return ResourceManager.GetString("UnableToDeleteDetailDataSetQueryConstraint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Не удалось получить параметры подключения к базе данных..
        '''</summary>
        Friend Shared ReadOnly Property UnableToGetDBConnectionParams() As String
            Get
                Return ResourceManager.GetString("UnableToGetDBConnectionParams", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Не удалось получить объект SBLogon.LoginPoint..
        '''</summary>
        Friend Shared ReadOnly Property UnableToGetLoginPoint() As String
            Get
                Return ResourceManager.GetString("UnableToGetLoginPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Не удалось получить объект {0}..
        '''</summary>
        Friend Shared ReadOnly Property UnableToGetObject() As String
            Get
                Return ResourceManager.GetString("UnableToGetObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ошибка получения sql-значения поля реквизита из именованного значения.
        '''Реквизит: {0}. Именованное значение: {1}.&quot;.
        '''</summary>
        Friend Shared ReadOnly Property UnableToGetRequisiteSqlFieldValueTemplate() As String
            Get
                Return ResourceManager.GetString("UnableToGetRequisiteSqlFieldValueTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Возникло исключение при попытке ограничить набор записей детального раздела компоненты {0}. Текст запроса AddWhere:
        '''&apos;{1}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property UnableToSpecifyDataSetQueryTemplate() As String
            Get
                Return ResourceManager.GetString("UnableToSpecifyDataSetQueryTemplate", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
